/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        gray: {
          100: "#fefefe",
          200: "#8d8d8d",
          300: "#030303",
          400: "#020202",
          500: "#010101",
          600: "rgba(255, 255, 255, 0.7)",
        },
        dimgray: "#505050",
        "pmi-dsm-color-white": "#fff",
        black: "#000",
        aqua: "#00ffff",
        gold: "#ffd800",
        crimson: "#dc4040",
        palegreen: "#65e674",
        springgreen: "rgba(0, 255, 102, 0.8)",
        royalblue: "#006bee",
        tomato: "#ff4343",
        "bgdanoff-new-fil": "#468d8d",
        "text-secondary-onlight": "#575757",
        "pmi-dsm-color-gray-100": "#f5f5f5",
        "pmi-dsm-color-gray-400": "#ababab",
        "pmi-dsm-color-red-500base": "#ec0030",
        "pmi-dsm-color-brand-primary-800": "#14042e",
        "text-primary-onlight": "#212121",
        "pmi-dsm-color-brand-primary-500base": "#4f17a8",
        "pmi-dsm-color-brand-primary-700": "#2f0e65",
        "text-subtext-grey": "#63717b",
        "greyscale-10": "#e6e6e6",
        "text-midnight-black-50": "#81919d",
        "secondary-hot-pink": "#c90766",
        "text-midnight-black": "#04243c",
        "m3-sys-light-surface": "#fef7ff",
        "schemes-outline-variant": "#cac4d0",
        "m3-sys-light-on-surface-variant": "#49454f",
        "m3-sys-light-on-surface": "#1d1b20",
        "m3-sys-light-primary-container": "#eaddff",
      },
      spacing: {
        "space-padding-xs": "8px",
        "space-padding-sm": "12px",
        "size-2xl": "40px",
        "size-lg": "24px",
        "space-padding-2xs": "4px",
        "layout-margin-xs": "8px",
        "size-sm": "8px",
      },
      fontFamily: {
        "ibm-plex-mono": "'IBM Plex Mono'",
        vt323: "VT323",
        "paragraph-sm": "Inter",
        "paragraph-x-small-regular": "'Source Sans Pro'",
        "m3-label-small": "Roboto",
      },
      borderRadius: {
        "8xs": "5px",
        xl: "20px",
        mini: "15px",
        "13xl": "32px",
        "9980xl": "9999px",
        "81xl": "100px",
        "radius-md": "4px",
        "radius-lg": "8px",
        "radius-circle": "9999px",
        "corner-large": "16px",
      },
    },
    fontSize: {
      "3xs": "10px",
      "5xs": "8px",
      "5xl": "24px",
      "2xs": "11px",
      sm: "14px",
      base: "16px",
      xs: "12px",
      lg: "18px",
      inherit: "inherit",
    },
    screens: {
      mq1275: {
        raw: "screen and (max-width: 1275px)",
      },
      mq1100: {
        raw: "screen and (max-width: 1100px)",
      },
      mq750: {
        raw: "screen and (max-width: 750px)",
      },
      mq450: {
        raw: "screen and (max-width: 450px)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
